DEBUG: False
TEMPLATE_DEBUG: False

SECRET_KEY: 'HIDE ME'

DATABASES:
  default:
    ENGINE: 'django.db.backends.sqlite3'
    NAME: '/var/lib/ci-status/db.sqlite3'

AUTH_LDAP_SERVER_URI: 'ldap://custom_server.net'
LDAP_GROUP_SETTINGS: 'cn=mirantis,ou=groups,o=mirantis,dc=mirantis,dc=net'
AUTH_LDAP_GROUP_SEARCH:
  base_dn: 'ou=groups,o=mirantis,dc=mirantis,dc=net'
  scope: 'SCOPE_SUBTREE'
  filterstr: '(objectClass=groupOfNames)'
AUTH_LDAP_USER_DN_TEMPLATE: 'uid=%(user)s,ou=people,o=mirantis,dc=mirantis,dc=net'
AUTH_LDAP_USERS_BASE_DN: 'ou=people,o=mirantis,dc=mirantis,dc=net'
AUTH_LDAP_GROUP_CACHE_TIMEOUT: 3600

STAFF_GROUPS:
  - 'ci'
  - 'devops-all'

INTERNAL_IPS:
  - '127.0.0.1'

CELERYBEAT_SCHEDULE:
  every_ten_minutes:
    task: 'ci_dashboard.tasks.synchronize'
    schedule:
      crontab:
        minute: '*/10'
